config/routes.rb
Demo::Application.routes.draw do

  get 'admin' => "admin#index"
  get "search/index"
  get "search/street"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :gynecologic_examinations
  resources :pregnancy_trimester_i_examinations
  resources :patients

  root :to => 'search#index'

end

app/controllers/search_controller.rb
# -*- encoding: utf-8 -*-
class SearchController < ApplicationController
  skip_before_filter :authorize_root
  def index
    if params[:term]
      args = params[:term].split
      4.times do |i|
        args[i] ||= ''
        args[i] += '%'
      end
      condition = 'last_name LIKE ? AND first_name LIKE ? AND patronymic LIKE ? AND dob LIKE ?'
      fields = [:id, :last_name, :first_name, :patronymic, :dob]
      result = Patient.select(fields).where(condition, *args).limit(5)
      @patients = []
      result.each do |item|
        @patients << {"id" => item.id, "label" => fields[1..-1].map{|f| item.send(f) }.join(' ') }
      end
    end
    
    respond_to do |format|
      format.html
      format.json { render :json => @patients }
    end
  end
  
  def street
    @streets = []
    @@streets_cache ||= YAML::load_file(Rails.root + 'db/streets.yml')
    if term = params[:term]
      re = Regexp.new(term)
      @streets = @@streets_cache.grep(re).first(5)
    end
    
    respond_to do |format|
      format.json { render :json => @streets }      
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<p id="notice" class="noprint"><%= notice %></p>
<script>
  $(function() {
    function encode_url(url, parameters) {
      var parametersEncoded = $.param(parameters);
      var seperator = url.indexOf('?') == -1 ? "?" : "&";
  
      return(url + seperator + parametersEncoded);
    }


    $("#autocomplete").autocomplete({
      autoFocus: false,
      delay: 1,
      source: "<%= search_index_path(:json) %>", // the same as "/search/index.json",
      minLength: 2,
      select: function( event, ui ) {
        // redirect to existing patient: GET /patients/:id
        var url = "<%= patients_path %>" + "/" + ui.item.id;
        $(location).attr("href", url);
      }
    });
    
    $("#autocomplete").keypress(function(e) {
      var keycode = (e.keyCode ? e.keyCode : e.which);
      if(keycode == 13)
      {
        var val = $("#autocomplete").val();
        // create new patient: GET /patients/new + term
        var url = "<%= new_patient_path %>"
        url = encode_url(url, {term: val});
        $(location).attr("href", url);
      }
    });
  });
</script>
<style>
body {
  text-align: center;
  margin: 0 auto;
}
.autocomplete_field {
  position: absolute;
  left: 50%;
  top: 50%;
  margin-left: -250px;
  margin-top: -150px;
}
ul.ui-autocomplete li.ui-menu-item {
  text-align: left;
}
</style>

<div class="autocomplete_field">
  <label for="autocomplete">Введите данные пациента (Ф.И.О., дата рождения) или выберите существующего из базы: </label><br />
  <input id="autocomplete" size="70"/>
</div>