config/routes.rb
Demo::Application.routes.draw do

  get 'admin' => "admin#index"
  get "search/index"
  get "search/street"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :gynecologic_examinations
  resources :pregnancy_trimester_i_examinations
  resources :patients

  root :to => 'search#index'

end

app/models/pregnancy_trimester_i_examination.rb
# encoding: UTF-8
class PregnancyTrimesterIExamination < ActiveRecord::Base
  has_many :patient_examinations
  has_many :patients, :through => :patient_examinations
  has_many :ovums, :dependent => :destroy
  belongs_to :left_ovary, :class_name => "PregnancyTrimesterIExamination::Ovary", :dependent => :destroy
  belongs_to :right_ovary, :class_name => "PregnancyTrimesterIExamination::Ovary", :dependent => :destroy
  belongs_to :ovaries
  accepts_nested_attributes_for :ovums, :allow_destroy => true
  accepts_nested_attributes_for :left_ovary, :allow_destroy => true
  accepts_nested_attributes_for :right_ovary, :allow_destroy => true
  attr_accessible :comments
  attr_accessible :gestation_age_in_weeks
  attr_accessible :left_ovary_id, :left_ovary
  attr_accessible :right_ovary_id, :right_ovary
  attr_accessible :user_id
  attr_accessible :uterus_anteroposterior
  attr_accessible :uterus_length
  attr_accessible :uterus_transverse_size
  attr_accessible :findings_and_recommendations
  attr_accessible :ovums_attributes
  attr_accessible :left_ovary_attributes
  attr_accessible :right_ovary_attributes

  validate :uterine_attributes
  
  def uterine_attributes
    if gestation_age_in_weeks.nil? || gestation_age_in_weeks <= 0
      errors.add(:gestation_age_in_weeks, "Значение не задано или недопустимо")
    end
    if uterus_anteroposterior.nil? || uterus_anteroposterior <= 0
      errors.add(:uterus_anteroposterior, "Значение не задано или недопустимо")
    end
    if uterus_length.nil? || uterus_length <= 0
      errors.add(:uterus_length, "Значение не задано или недопустимо")
    end
    if uterus_transverse_size.nil? || uterus_transverse_size <= 0
      errors.add(:uterus_transverse_size, "Значение не задано или недопустимо")
    end
  end
end

app/models/pregnancy_trimester_i_examination/ovary.rb
# encoding: UTF-8
class PregnancyTrimesterIExamination::Ovary < ActiveRecord::Base
  has_one :pregnancy_trimester_i_examination
  attr_accessible :is_visible
  attr_accessible :length
  attr_accessible :width
  attr_accessible :anteroposterior
  attr_accessible :is_yellow_body_present
  attr_accessible :yellow_body_diameter
  validate :check_attributes
  
  def check_attributes
    if is_visible
      if length.nil? || length <= 0
        errors.add(:length, "Значение не задано или недопустимо.")
      end
      if width.nil? || width <= 0
        errors.add(:width, "Значение не задано или недопустимо.")
      end
      if anteroposterior.nil? || anteroposterior <= 0
        errors.add(:anteroposterior, "Значение не задано или недопустимо.")
      end
      if is_yellow_body_present
        if yellow_body_diameter.nil? || yellow_body_diameter <= 0
          errors.add(:yellow_body_diameter, "Значение не задано или недопустимо.")
        end
      end
    end
  end
end

app/models/pregnancy_trimester_i_examination/ovum.rb
# encoding: UTF-8
class PregnancyTrimesterIExamination::Ovum < ActiveRecord::Base
  belongs_to :pregnancy_trimester_i_examination
  belongs_to :localization
  has_many :fetuses, :dependent => :destroy
  accepts_nested_attributes_for :fetuses, :allow_destroy => true
  attr_accessible :localization_id, :localization
  attr_accessible :length
  attr_accessible :anteroposterior
  attr_accessible :median_inner_diameter
  attr_accessible :gestation_age_in_weeks
  attr_accessible :fetuses_attributes
  validate :check_attributes
  
  def check_attributes
    if length.nil? || length <= 0
      errors.add(:length, "Значение не задано или недопустимо")
    end
    if anteroposterior.nil? || anteroposterior <= 0
      errors.add(:anteroposterior, "Значение не задано или недопустимо")
    end
    if median_inner_diameter.nil? || median_inner_diameter <= 0
      errors.add(:median_inner_diameter, "Значение не задано или недопустимо")
    end
    if gestation_age_in_weeks.nil? || gestation_age_in_weeks <= 0
      errors.add(:gestation_age_in_weeks, "Значение не задано или недопустимо")
    end
  end
end

app/models/pregnancy_trimester_i_examination/ovum/fetus.rb
# encoding: UTF-8
class PregnancyTrimesterIExamination::Ovum::Fetus < ActiveRecord::Base
  belongs_to :ovum
  attr_accessible :coccyx_parietal_size
  attr_accessible :biparietal_size
  attr_accessible :is_fetal_cardiac_activity_manifested
  attr_accessible :ovum_id
  validate :check_attributes
  
  def check_attributes
    if biparietal_size.nil? || biparietal_size <= 0
      errors.add(:biparietal_size, 'Значение не задано или недопустимо.')
    end
    if coccyx_parietal_size.nil? || coccyx_parietal_size <= 0
      errors.add(:coccyx_parietal_size, 'Значение не задано или недопустимо.')
    end
  end
end

app/models/pregnancy_trimester_i_examination/ovum/localization.rb
class PregnancyTrimesterIExamination::Ovum::Localization < ActiveRecord::Base
  has_many :ovums
  attr_accessible :value
end

app/controllers/pregnancy_trimester_i_examinations_controller.rb
# encoding: UTF-8
class PregnancyTrimesterIExaminationsController < ApplicationController
  skip_before_filter :authorize_root, :only => [:show, :new, :edit, :create, :update]
  # GET /pregnancy_trimester_i_examinations
  # GET /pregnancy_trimester_i_examinations.json
  def index
    @pregnancy_trimester_i_examinations = PregnancyTrimesterIExamination.find(
      :all,
      :joins => [:patient_examinations, :patients],
      :order => ['patients.last_name, patients.first_name, patients.patronymic, patients.dob', :created_at])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pregnancy_trimester_i_examinations }
    end
  end

  # GET /pregnancy_trimester_i_examinations/1
  # GET /pregnancy_trimester_i_examinations/1.json
  def show
    @pregnancy_trimester_i_examination = PregnancyTrimesterIExamination.find(params[:id])
    @patient = @pregnancy_trimester_i_examination.patients.first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pregnancy_trimester_i_examination }
    end
  end

  # GET /pregnancy_trimester_i_examinations/new
  # GET /pregnancy_trimester_i_examinations/new.json
  def new
    @pregnancy_trimester_i_examination = PregnancyTrimesterIExamination.new
    @pregnancy_trimester_i_examination.build_left_ovary
    @pregnancy_trimester_i_examination.build_right_ovary

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pregnancy_trimester_i_examination }
    end
  end

  # GET /pregnancy_trimester_i_examinations/1/edit
  def edit
    @pregnancy_trimester_i_examination = PregnancyTrimesterIExamination.find(params[:id])
  end

  # POST /pregnancy_trimester_i_examinations
  # POST /pregnancy_trimester_i_examinations.json
  def create
    @pregnancy_trimester_i_examination = PregnancyTrimesterIExamination.new(params[:pregnancy_trimester_i_examination])
    @pregnancy_trimester_i_examination.user_id = session[:user_id]
    if params[:patient_id]
      respond_to do |format|
        if @pregnancy_trimester_i_examination.save
          PatientExamination.create(:patient_id => params[:patient_id], :pregnancy_trimester_i_examination_id => @pregnancy_trimester_i_examination.id).save
          format.html { redirect_to @pregnancy_trimester_i_examination, notice: 'Отчет успешно создан.' }
          format.json { render json: @pregnancy_trimester_i_examination, status: :created, location: @pregnancy_trimester_i_examination }
        else
          format.html { render action: "new" }
          format.json { render json: @pregnancy_trimester_i_examination.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :root, notice: 'Невозможно создать отчет без привязки к пациенту. Для создания отчета используйте карту пациента.'
    end
  end

  # PUT /pregnancy_trimester_i_examinations/1
  # PUT /pregnancy_trimester_i_examinations/1.json
  def update
    @pregnancy_trimester_i_examination = PregnancyTrimesterIExamination.find(params[:id])

    respond_to do |format|
      if @pregnancy_trimester_i_examination.update_attributes(params[:pregnancy_trimester_i_examination])
        format.html { redirect_to @pregnancy_trimester_i_examination, notice: 'Данные отчета обновлены.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pregnancy_trimester_i_examination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pregnancy_trimester_i_examinations/1
  # DELETE /pregnancy_trimester_i_examinations/1.json
  def destroy
    @pregnancy_trimester_i_examination = PregnancyTrimesterIExamination.find(params[:id])
    @patient = @pregnancy_trimester_i_examination.patients.first
    PatientExamination.where(:pregnancy_trimester_i_examination_id => @pregnancy_trimester_i_examination.id).each {|exam| exam.destroy }
    @pregnancy_trimester_i_examination.destroy

    respond_to do |format|
      format.html { redirect_to patient_path(@patient) }
      format.json { head :no_content }
    end
  end
end

app/helpers/pregnancy_trimester_i_examinations_helper.rb
module PregnancyTrimesterIExaminationsHelper
end

app/views/pregnancy_trimester_i_examinations/_form.html.erb
<script type="text/javascript">
  function set_disabled_attribute(selector, attributes, state) {
    $.each(attributes, function(attribute, value) {
      $(selector + '_' + attribute).prop('disabled', state);
    });
  };

  function set_value(selector, attributes) {
    $.each(attributes, function(attribute, value) {
      var sel = selector + '_' + attribute;
      if($(sel).prop('type') == 'checkbox') {
        $(sel).prop('checked', value);
      }
      else {
        $(sel).val(value);
      }
    });
  };
  
  function set_option(selector, options, position) {
    $.each(options, function(option, value) {
      $(selector + '_' + option + ' :' + position).prop('selected', true);
    });
  };
  
  function toggle_yellow_body_condition(is_checked, selector, attributes) {
    if(is_checked) {
      set_disabled_attribute(selector, attributes, false);
    }
    else {
      set_disabled_attribute(selector, attributes, true);
      set_value(selector, attributes);
    }
  }
  
  function toggle_ovary_condition(is_checked, selector, attributes) {
    if(is_checked) {
      set_disabled_attribute(selector, attributes, false);
      toggle_yellow_body_condition(false, selector, yellow_body_attributes);
    }
    else {
      set_disabled_attribute(selector, attributes, true);
      toggle_yellow_body_condition(false, selector, yellow_body_attributes);
      set_value(selector, attributes);
    }
  }
  
  function get_ovums() {
    return $('form div.fields span.on_one_line a.remove_nested_fields[data-association=ovums]');
  }
  
  $(document).ready(function() {
    submit_flag = false;

    default_selector = '#pregnancy_trimester_i_examination';
    left_ovary_selector = default_selector + '_' + 'left_ovary_attributes';
    right_ovary_selector = default_selector + '_' + 'right_ovary_attributes';
    ovary_attributes = {'length': '', 'width': '', 'anteroposterior': '', 'is_yellow_body_present': false};
    yellow_body_attributes = {'yellow_body_diameter': ''};
    
    /////////////////////////////////////
    // initial consistensy
    /////////////////////////////////////
    
    ovums = get_ovums();
    if( ovums.length == 0 ) {
      // add one ovum by default
      $('form a.add_nested_fields[data-association=ovums]').click();
      ovums = get_ovums();
      first_ovum = ovums.parent().parent();
      // add one fetus by default
      first_ovum.find('a.add_nested_fields[data-association=fetuses]').click();
      // hide remove link of the first ovum and fetus
      first_ovum.find('span.on_one_line a.remove_nested_fields[data-association=ovums]').hide();
      first_ovum.find('div div.fields span.on_one_line a.remove_nested_fields[data-association=fetuses]').hide();
    }
    else {
      ovums = get_ovums().parent().parent();
      // hide remove link of the first ovum
      ovums.slice(0, 1).find('span.on_one_line a.remove_nested_fields[data-association=ovums]').hide();
      $.each(ovums, function(e) {
        // hide remove link for each first fetus
        $(this).find('div.fields span.on_one_line a.remove_nested_fields[data-association=fetuses]').slice(0, 1).hide();
      })
    }

    // left ovary
    if( !$(left_ovary_selector + '_' + 'is_yellow_body_present').is(':checked') ) {
      set_disabled_attribute(left_ovary_selector, yellow_body_attributes, true);
    }
    
    if( !$(left_ovary_selector + '_' + 'is_visible').is(':checked') ) {
      set_disabled_attribute(left_ovary_selector, ovary_attributes, true);      
    }
    
    // right ovary
    if( !$(right_ovary_selector + '_' + 'is_yellow_body_present').is(':checked') ) {
      set_disabled_attribute(right_ovary_selector, yellow_body_attributes, true);
    }

    if( !$(right_ovary_selector + '_' + 'is_visible').is(':checked') ) {
      set_disabled_attribute(right_ovary_selector, ovary_attributes, true);      
    }
    
    /////////////////////////////////////
    // change detectors
    /////////////////////////////////////
    
    $(document).on('nested:fieldAdded:ovums', function(e) {
      add_link = e.field.find('div a.add_nested_fields[data-association=fetuses]');
      add_link.click();
      remove_fetus_link = e.field.find('div div.fields span.on_one_line a.remove_nested_fields[data-association=fetuses]')
      remove_fetus_link.hide();
    });

    // left ovary
    $(left_ovary_selector + '_' + 'is_yellow_body_present').change(function(e) {
      toggle_yellow_body_condition(e.currentTarget.checked, left_ovary_selector, yellow_body_attributes);
    });
    
    $(left_ovary_selector + '_' + 'is_visible').change(function(e) {
      toggle_ovary_condition(e.currentTarget.checked, left_ovary_selector, ovary_attributes)
    });
    
     // right ovary
    $(right_ovary_selector + '_' + 'is_yellow_body_present').change(function(e) {
      toggle_yellow_body_condition(e.currentTarget.checked, right_ovary_selector, yellow_body_attributes);
    });
    
    $(right_ovary_selector + '_' + 'is_visible').change(function(e) {
      toggle_ovary_condition(e.currentTarget.checked, right_ovary_selector, ovary_attributes)
    });    

    /////////////////////////////////////
    // reenable attributes before submit
    /////////////////////////////////////
    
    $('form').submit(function(){
      // left ovary
      set_disabled_attribute(left_ovary_selector,
                             yellow_body_attributes,
                             false);

      set_disabled_attribute(left_ovary_selector,
                             ovary_attributes,
                             false);

      // right ovary
      set_disabled_attribute(right_ovary_selector,
                             yellow_body_attributes,
                             false);

      set_disabled_attribute(right_ovary_selector,
                             ovary_attributes,
                             false);
    });

    $('input[name=commit][type=submit]').click(function(e) {
      submit_flag = true;
    });

    $(window).on('beforeunload', function() {
      if(submit_flag) {
        return;
      }
      else {
        return "Вы собираетесь покинуть страницу. Все несохраненные данные будут потеряны.";
      }
    });
  });
</script>
<% @form = @pregnancy_trimester_i_examination %>
<%= nested_form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2>Из-за <%= ec = @form.errors.count %> <%= Russian.p(ec, "ошибки", "ошибок", "ошибок") %> отчет сохранить не удалось:</h2>

      <ul>
      <% @form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    Плодные яйца:
  </div>
  <%= f.fields_for :ovums do |builder| %>
    <%= render 'ovum', :o => builder %>
  <% end %>
  <%= f.link_to_add '[+] плодное яйцо', :ovums %>
  <br />
  <br />
  <fieldset>
    <legend>Размеры матки</legend>
      <div class="fieldset">
        <span class="on_one_line">
          <%= f.label :uterus_length %><br />
          <%= f.number_field :uterus_length, :style => "width:50px;", :step => "any" %>
        </span>
        <span class="on_one_line">
          <%= f.label :uterus_anteroposterior %><br />
          <%= f.number_field :uterus_anteroposterior, :style => "width:50px;", :step => "any" %>
        </span>
        <span class="on_one_line">
          <%= f.label :uterus_transverse_size %><br />
          <%= f.number_field :uterus_transverse_size, :style => "width:50px;", :step => "any" %>
        </span>
      </div>
      <div class="field">соответствуют
        <%= f.number_field :gestation_age_in_weeks, :style => "width:40px;" %> <%= f.label :gestation_age_in_weeks %>
      </div>
  </fieldset>
  <fieldset>
    <legend>Левый яичник</legend>
    <%= f.fields_for :left_ovary do |builder| %>
      <%= render "ovary", :o => builder %>
    <% end %>
  </fieldset>
  <fieldset>
    <legend>Правый яичник</legend>
    <%= f.fields_for :right_ovary do |builder| %>
      <%= render "ovary", :o => builder %>
    <% end %>
  </fieldset>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments, :size => "71x7" %>
  </div>
  <fieldset>
    <legend><%= f.label :findings_and_recommendations %></legend>
    <div class="field">
      <%= f.text_area :findings_and_recommendations, :size => "70x7" %>
    </div>
  </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= hidden_field_tag 'patient_id', params[:patient_id] %>
<% end %>

app/views/pregnancy_trimester_i_examinations/_ovary.html.erb
<div class="fieldset">
  <span class="on_one_line"><br />
    <%= o.label :is_visible %>
    <%= o.check_box :is_visible %>
  </span>
  <span class="on_one_line">
    <%= o.label :length %><br />
    <%= o.number_field :length, :style => "width:50px;", :step => "any" %>
  </span>
  <span class="on_one_line">
    <%= o.label :width %><br />
    <%= o.number_field :width, :style => "width:50px;", :step => "any" %>
  </span>
  <span class="on_one_line">
    <%= o.label :anteroposterior %><br />
    <%= o.number_field :anteroposterior, :style => "width:50px;", :step => "any" %>
  </span>
  <span class="on_one_line"><br />
    <%= o.label :is_yellow_body_present %>
    <%= o.check_box :is_yellow_body_present %>
  </span>
  <span class="on_one_line">
    <%= o.label :yellow_body_diameter %><br />
    <%= o.number_field :yellow_body_diameter, :style => "width:50px;", :step => "any" %>
  </span>
</div>

app/views/pregnancy_trimester_i_examinations/_ovum.html.erb
<span class="on_one_line">
  <%= o.label :localization_id %><br />
  <%= o.collection_select :localization_id, PregnancyTrimesterIExamination::Ovum::Localization.all, :id, :value %>
</span>
<span class="on_one_line">
  <%= o.label :length %><br />
  <%= o.number_field :length, :style => "width:50px;", :step => "any" %>
</span>
<span class="on_one_line">
  <%= o.label :anteroposterior %><br />
  <%= o.number_field :anteroposterior, :style => "width:50px;", :step => "any" %>
</span>
<span class="on_one_line">
  <%= o.label :median_inner_diameter %><br />
  <%= o.number_field :median_inner_diameter, :style => "width:50px;", :step => "any" %>
</span>
<span class="on_one_line"><br/>
  соответствуют <%= o.number_field :gestation_age_in_weeks, :style => "width:50px;" %> <%= o.label :gestation_age_in_weeks %>
</span>
<span class="on_one_line">
  <br /><%= o.link_to_remove "[-] плодное яйцо" %>
</span>
<div>
  Эмбрионы:
</div>
<%= o.fields_for :fetuses do |builder| %>
  <span class="on_one_line">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </span>
  <span class="on_one_line">
    <%= builder.label :coccyx_parietal_size %><br />
    <%= builder.number_field :coccyx_parietal_size, :style => "width:50px;", :step => "any"  %>
  </span>
  <span class="on_one_line">
    <%= builder.label :biparietal_size %><br />
    <%= builder.number_field :biparietal_size, :style => "width:50px;", :step => "any"  %>
  </span>
  <span class="on_one_line"><br />
    <%= builder.label :is_fetal_cardiac_activity_manifested %>
    <%= builder.check_box :is_fetal_cardiac_activity_manifested  %>
  </span>
  <span class="on_one_line">
    <br /><%= builder.link_to_remove "[-] эмбрион" %>
  </span>
<% end %>
<div>
  <%= o.link_to_add "[+] эмбрион", :fetuses %>
</div>

app/views/pregnancy_trimester_i_examinations/edit.html.erb
<h1>Редактирование обследования на беременность в I-ом триместре</h1>

<%= render 'form' %>

app/views/pregnancy_trimester_i_examinations/index.html.erb
<h1>Список обследований на беременность в первом триместре</h1>
<table>
  <tr>
    <th>Ф.И.О.</th>
    <th>Дата</th>
    <th></th>

  </tr>

<% @pregnancy_trimester_i_examinations.each do |exam| %>
  <tr class="<%= cycle('', 'alt') %>">
    <td><%= link_to format_name(exam.patients.first), patient_path(exam.patients.first) %></td>
    <td><%= l exam.created_at, :format => :long %></td>
    <td><%= link_to 'Показать', exam %> |
        <%= link_to 'Редактировать', edit_gynecologic_examination_path(exam) %> |
        <%= link_to 'Удалить', exam, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  </tr>
<% end %>
</table>

app/views/pregnancy_trimester_i_examinations/new.html.erb
<h1>Новое обследование на беременность в I-ом триместре</h1>

<%= render 'form' %>

app/views/pregnancy_trimester_i_examinations/show.html.erb
<% @pti_exam = @pregnancy_trimester_i_examination %>
<p id="notice" class="noprint"><%= notice %></p>
<h4>Ультразвуковая диагностика в I триместре беременности</h4>
<h4>на аппарате Sono Ace R3 фирмы Medison</h4>
<p class="headline">(ул. Розы Люксембург, д.77, тел. 46-15-10)</p>
<p>
  <br/>
</p>
<p>
  Ф.И.О. <%= format_name(@patient) %>, возраст <%= patient_age = age(@patient.dob)%> <%= Russian.p(patient_age, 'год', 'года', 'лет') %>.<br />
</p>
<p>
  Имеется <%= amount = @pti_exam.ovums.size %> <%= Russian.p(amount, 'плодное яйцо', 'плодных яйца', 'плодных яиц') %>.
  <% if amount == 1 then ovum = @pti_exam.ovums.first %>
    <!-- 1 плодное яйцо -->
    Расположено <%= ovum.localization.value %>.
    Размеры плодного яйца (длина <%= ovum.length %> мм, передне-задний размер <%= ovum.anteroposterior %> мм, СВДПЯ <%= ovum.median_inner_diameter %> мм) соответствуют <%= oga = ovum.gestation_age_in_weeks %> <%= Russian.p(oga, 'неделе', 'неделям', 'неделям') %> беременности.<br />
    <% if ovum.fetuses.size == 1 then fetus = ovum.fetuses.first %>
      Копчико-теменной размер <%= fetus.coccyx_parietal_size %> мм, бипариетальный размер <%= fetus.biparietal_size %> мм. Сердечная деятельность <%= 'не' unless fetus.is_fetal_cardiac_activity_manifested? %> определяется.
    <% else %>Эмбрионы:
      <ol>
      <% ovum.fetuses.each do |fetus| %>
        <li>Копчико-теменной размер <%= fetus.coccyx_parietal_size %> мм, бипариетальный размер <%= fetus.biparietal_size %> мм. Сердечная деятельность <%= 'не' unless fetus.is_fetal_cardiac_activity_manifested? %> определяется.</li>
      <% end %>
      </ol>
    <% end %>
  <% else %><br />
    <!-- несколько плодных яиц -->
    <ul>
    <% @pti_exam.ovums.each do |ovum| %>
      <li><%= l = ovum.localization.value; l[0] = 'В'; l %>. Размеры: длина <%= ovum.length %> мм, передне-задний размер <%= ovum.anteroposterior %> мм, СВДПЯ <%= ovum.median_inner_diameter %> мм, соответствуют <%= oga = ovum.gestation_age_in_weeks %> <%= Russian.p(oga, 'неделе', 'неделям', 'неделям') %> беременности.
      <% if ovum.fetuses.size == 1 then fetus = ovum.fetuses.first %>
        Копчико-теменной размер <%= fetus.coccyx_parietal_size %> мм, бипариетальный размер <%= fetus.biparietal_size %> мм. Сердечная деятельность <%= 'не' unless fetus.is_fetal_cardiac_activity_manifested? %> определяется.
      <% else %>Эмбрионы:
        <ol>
        <% ovum.fetuses.each do |fetus| %>
        <li>Копчико-теменной размер <%= fetus.coccyx_parietal_size %> мм, бипариетальный размер <%= fetus.biparietal_size %> мм. Сердечная деятельность <%= 'не' unless fetus.is_fetal_cardiac_activity_manifested? %> определяется.</li>
        <% end %>
        </ol>
      <% end %>
      </li>
    <% end %>
    </ul>
  <% end %>
</p>
<p>
  Особенности:
  размеры матки (длина <%= @pti_exam.uterus_length %> мм,
  передне-задний размер <%= @pti_exam.uterus_anteroposterior %> мм,
  поперечный размер <%= @pti_exam.uterus_transverse_size %> мм) соответствуют
  <%= ga = @pti_exam.gestation_age_in_weeks %> <%= Russian.p(ga, 'неделе', 'неделям', 'неделям') %> беременности.
</p>

<p>
  <% lo = @pti_exam.left_ovary; ro = @pti_exam.right_ovary %>
  Левый яичник:
    <% if lo.is_visible? %>
      длина <%= lo.length %> мм, ширина <%= lo.width %> мм, передне-задний <%= lo.anteroposterior %> мм.<br />
    <% else %>
      не определяется.<br />
    <% end %>
  Правый яичник: 
    <% if ro.is_visible? %>
      длина <%= ro.length %> мм, ширина <%= ro.width %> мм, передне-задний <%= ro.anteroposterior %> мм.<br />
    <% else %>
      не определяется.<br />
    <% end %>
  <% if lo.is_yellow_body_present? && ro.is_yellow_body_present? %>
    Желтое тело в обоих яичниках, диаметр левого <%= lo.yellow_body_diameter %> мм, правого - <%= ro.yellow_body_diameter %> мм.
  <% elsif lo.is_yellow_body_present? || ro.is_yellow_body_present? %>
    Желтое тело в <%= yb = (lo.is_yellow_body_present?) ? ['левом', lo.yellow_body_diameter] : ['правом', ro.yellow_body_diameter]; yb.first %> яичнике, диаметр <%= yb.last %> мм.
  <% else %>
    Желтое тело не обнаружено.
  <% end %>
</p>

<p>
  <%= @pti_exam.comments %>
</p>

<p>
  <b><em><u>Заключение и рекомендации</u></em></b><br/>
  <%= @pti_exam.findings_and_recommendations %>
</p>

<p>
  <%= l @pti_exam.created_at.to_date, :format => :long %><br />
  Врач: <%= format_name(current_user, :format => :abbr) %>
</p>

<p class="noprint">
  <%= link_to 'Редактировать', edit_pregnancy_trimester_i_examination_path(@pti_exam) %> |
  <%= link_to 'К пациенту', patient_path(@patient) %>
  <% if current_user.is_root? %> |
    <%= link_to 'Удалить', @pti_exam, method: :delete, data: { confirm: 'Вы уверены?' } %>
  <% end %>
</p>

<p class="noprint">
  <input type="button" id="print" onclick="javascript:print()" value="Печать" />
</p>