config/routes.rb
Demo::Application.routes.draw do

  get 'admin' => "admin#index"
  get "search/index"
  get "search/street"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :gynecologic_examinations
  resources :pregnancy_trimester_i_examinations
  resources :patients

  root :to => 'search#index'

end

app/models/patient.rb
# -*- encoding: utf-8 -*-
class Patient < ActiveRecord::Base
  belongs_to :sex
  belongs_to :address, :dependent => :destroy
  has_many :patient_examinations
  has_many :gynecologic_examinations, :through => :patient_examinations
  has_many :pregnancy_trimester_i_examinations, :through => :patient_examinations
  accepts_nested_attributes_for :address, :allow_destroy => true
  attr_accessible :dob, :first_name, :last_name, :patronymic, :phone
  attr_accessible :sex_id, :sex
  attr_accessible :address_id, :address
  attr_accessible :address_attributes
  validates :last_name, :first_name, :patronymic, :dob, :sex_id, :presence => true
  validates_uniqueness_of :last_name, :scope => [:first_name, :patronymic, :dob], :message => 'Пациент с такими данными уже есть в базе'
  validate :dob_check
  validate :phone_format

  def dob_check
    today = Date.today
    unless dob.nil?
      if today - 113.years < dob and dob < today
        return true
      else
        errors.add(:dob, "Дата рождения вне диапазона: #{today - 113.years} - #{today}")
        return false
      end
    end
  end

  def phone_format
    return true if phone.nil? || phone.empty?
    value = phone.gsub(/\s|-|\(|\)/,'') # удалить пробелы, тире, скобки
    errors.add(:phone, "неверный формат данных: #{phone}") unless value =~ /^((\+7|8)\d{10}|^((\+7|8)8332)?\d{6})/
  end
end

app/controllers/patients_controller.rb
# -*- encoding: utf-8 -*-
class PatientsController < ApplicationController
  skip_before_filter :authorize_root, :only => [:show, :new, :edit, :create, :update]
  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all(:order => [:last_name, :first_name, :patronymic, :dob])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new
    @patient.build_address

    if params[:term]
      data = params[:term].split
      @patient.last_name = data[0]
      @patient.first_name = data[1]
      @patient.patronymic = data[2]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Учетная карточка пациента заведена.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Данные пациента обновлены.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    PatientExamination.where(:patient_id => @patient.id).each do |pe|
      pe.examination.destroy
      pe.destroy
    end
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
  def format_address(addr)
    [addr.city + (!(addr.city.nil? || addr.city.empty?) && !(addr.street.nil? || addr.street.empty?) ? ',' : '' ), 
     addr.street,
     addr.house + (!(addr.house.nil? || addr.house.empty?) && !addr.appartment.nil? ? ',' : '' ),
     addr.appartment].join(' ')
  end
end

app/views/patients/_address.html.erb
<script>
  $(function() {
    $("#autocomplete").autocomplete({
      autoFocus: false,
      delay: 0,
      source: "<%= search_street_path(:json) %>", // то же самое что и "/search/street.json",
      minLength: 0
    });
  });
</script>
<style>
ul.ui-autocomplete li.ui-menu-item {
  text-align: left;
}
</style>
<div class="field">
  <span class="on_one_line">
    <%= f.label :city %><br />
    <%= f.text_field :city, :size => 15, :value => @patient.address.city || "Киров" %>
  </span>
  <span class="on_one_line">
    <%= f.label :street %><br />
    <%= f.text_field :street, :id => "autocomplete", :size => 30 %>
  </span>
  <span class="on_one_line">
    <%= f.label :house %><br />
    <%= f.text_field :house, :size => 3 %>
  </span>
  <span class="on_one_line">
    <%= f.label :appartment %><br />
    <%= f.text_field :appartment, :size => 3 %>
  </span>
</div>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation" class="noprint">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :patronymic %><br />
    <%= f.text_field :patronymic %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.text_field :dob, :id => "datepicker", :size => 10 %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.collection_select :sex_id, Sex.all, :id, :value %>
  </div>
  <div class="field">
    <%= f.fields_for :address do |builder| %>
      <%= render "address", :f => builder %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone, :size => 15 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<script type="text/javascript">
  // инициализировать календарь
  $(function() {
    $('#datepicker').datepicker(
      $.extend(      
        $.datepicker.regional[ "ru" ],
        {
          dateFormat: "yy-mm-dd",
          yearRange: "-113:+0",
          changeMonth: true,
          changeYear: true
        }
      )
    );
  });
  // перевести фокус на первое пустое поле
  $(function() {
    if( !$("#patient_last_name").val() ) {
      $("#patient_last_name").focus();
    } else if( !$("#patient_first_name").val() ) {
      $("#patient_first_name").focus();
    } else if( !$("#patient_patronymic").val() ) {
      $("#patient_patronymic").focus();
    } else if( !$("#datepicker").val() ) {
      $("#datepicker").focus();
    };
  });
</script>
<h1>Редактирование пациента</h1>

<%= render 'form' %>

<%= link_to 'Показать', @patient %> |
<%= link_to 'Назад', patients_path %>

app/views/patients/index.html.erb
<h1>Список пациентов</h1>

<table>
  <tr>
    <th>Фамилия</th>
    <th>Имя</th>
    <th>Отчество</th>
    <th>Дата рождения</th>
    <th></th>
  </tr>

<% @patients.each do |patient| %>
  <tr class="<%= cycle('', 'alt') %>">
    <td><%= patient.last_name %></td>
    <td><%= patient.first_name %></td>
    <td><%= patient.patronymic %></td>
    <td><%= patient.dob %></td>
    <td><%= link_to 'Показать', patient %> |
        <%= link_to 'Редактировать', edit_patient_path(patient) %> |
        <%= link_to 'Удалить', patient, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Создать пациента', new_patient_path %>

app/views/patients/new.html.erb
<script type="text/javascript">
  // инициализировать календарь
  $(function() {
    $('#datepicker').datepicker(
      $.extend(      
        $.datepicker.regional[ "ru" ],
        {
          dateFormat: "yy-mm-dd",
          yearRange: "-113:+0",
          changeMonth: true,
          changeYear: true
        }
      )
    );
  });
  // перевести фокус на первое пустое поле
  $(function() {
    if( !$("#patient_last_name").val() ) {
      $("#patient_last_name").focus();
    } else if( !$("#patient_first_name").val() ) {
      $("#patient_first_name").focus();
    } else if( !$("#patient_patronymic").val() ) {
      $("#patient_patronymic").focus();
    } else if( !$("#datepicker").val() ) {
      $("#datepicker").focus();
    };
  });
</script>
<h1>Создать пациента</h1>

<%= render 'form' %>

<%= link_to 'Назад', patients_path %>

app/views/patients/show.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('#submit_examination_select').click(function() {
      $(location).attr('href', $('#new_examination').val());
    })
  })
</script>
<p id="notice" class="noprint"><%= notice %></p>
<h1>Карта пациента</h1>
<p>
  <b>ФИО:</b>
  <%= format_name(@patient) %>
</p>

<p>
  <b>Возраст:</b>
  <%= a = age(@patient.dob) %> <%= Russian.p(a, 'год', 'года', 'лет') %>
</p>

<p>
  <b>Телефон:</b>
  <%= @patient.phone %>
</p>

<p>
  <b>Адрес:</b>
  <%= format_address(@patient.address) %>
</p>

<p>
  <b>Предыдущие обследования:</b><br />
  <% @patient.patient_examinations.order(:created_at).each do |pe| %>
    <%= l pe.created_at, :format => :long %>
    <%= link_to t(pe.examination_type, scope: [:activerecord, :models]), self.send("#{pe.examination_type.to_s}_path", pe.examination) %><br />
  <% end %>
</p>

<p class="noprint">
  Новое: <%= select(nil, nil, PatientExamination.examinations.collect{|pe| [t(pe, scope: [:activerecord, :models]), self.send("new_#{pe.to_s}_path", :patient_id => @patient.id)]}, {}, {:id => "new_examination"}) %>
  <input id="submit_examination_select" type="submit" value="Создать" />
<p>

<p class="noprint">
  <%= link_to 'Редактировать данные пациента', edit_patient_path(@patient) %>
</p>